name: Setup Dependencies
description: Install project dependencies

inputs:
  python-version:
    description: Python version to install
    required: true

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v3
      with: {python-version: "${{ inputs.python-version }}"}
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ inputs.python-version }}-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ inputs.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install -U pip setuptools wheel
        python -m pip install -r requirements.txt
      shell: bash
