name: CI

on: push

jobs:
  build-grammar:
    runs-on: ubuntu-latest
    name: Build Zoia Grammar
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@1.1.0
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 8 # ANTLR needs Java 8
      - name: Download ANTLR4
        run: ./scripts/prereq.sh
      - name: Build Zoia
        run: ./scripts/build.sh
      - name: Check that diff is empty
        run: git diff --quiet
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # We need at least 3.10 (dataclasses with slots)
        python-version: [ '3.10', '3.11-dev' ]
    name: Run Zoia Tests on Python ${{ matrix.python-version }}
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt
      - name: Test Zoia
        run: python -m pytest
