name: CI
on: push

jobs:
  build-grammar:
    runs-on: ubuntu-latest
    name: Build Zoia Grammar
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@1.1.0
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 8 # ANTLR needs Java 8
      - name: Setup dependencies
        uses: ./.github/actions/setup-deps
        with:
          python-version: '3.10'
      - name: Download ANTLR4
        run: ./scripts/prereq.sh
      - name: Build Zoia
        run: ./scripts/build.sh
      - name: Check that diff is empty
        run: git diff --quiet
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # TODO: waiting for coverage.py 6.3
        python-version: [ '3.10' ] #, '3.11-dev' ]
    name: Runs checks on Python ${{ matrix.python-version }}
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
      - name: Setup dependencies
        uses: ./.github/actions/setup-deps
        with:
          python-version: ${{ matrix.python-version }}
      - name: Lint Zoia
        run: python -m pylint src
      - name: Test Zoia
        run: coverage run -m pytest
      - name: Upload coverage data to coveralls.io
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
